### ISSUE TITLE
订阅代理规则建议

### ISSUE THREAD

**Issue by jmireles7** [SoDa-GitHub/shadowsocksrr-csharp#1]
客户端订阅默认是走代理更新的，初衷应该是为了订阅链接被BAN可以更新到，然而正常使用中很少有订阅链接被BAN的，而这个默认规则却直接导致修改了协议混淆参数后无法自动获取最新的设置，需要手动不使用代理更新，建议改为默认直连更新订阅！

**Comment by SoDa-GitHub** [comment]
这个问题已经被修正了，现在就是默认直联更新。
如果你是英文版，你可以发现原来括号里是bypass proxy，现在是use proxy（也就是说对调过了）。
总之这个反人类的设计已经被修正了。

**Comment by jmireles7** [comment]
@SoDa-GitHub   感谢大佬的神速回复，刚刚已经看了一下，确实如大佬所说已经修正这个反人类的设计。但是好像有点个小毛病，我的桌面语言是中文，而use proxy那句显示的是英文！

**Comment by SoDa-GitHub** [comment]
那个英文下个版本会修复。

**Comment by jmireles7** [comment]
感谢大佬无私奉献！
