### ISSUE TITLE
加密没有aes-gcm

### ISSUE THREAD

**Issue by jbxiaoyu** [SoDa-GitHub/shadowsocksrr-csharp#19]
加密没有aes-gcm

**Comment by TheCGDF** [comment]
恭喜transfer后喜提第一个&沙雕issue

**Comment by jbxiaoyu** [comment]
你不准备解决吗？那就算了当我没说

**Comment by shikkoku** [comment]
SSR原版本身就不支持ahead，谈何解决？

**Comment by jbxiaoyu** [comment]
> SSR原版本身就不支持ahead，谈何解决？

因为SSR已经2年以上不更新了啊。SS也不是一开始就支持的啊

**Comment by shikkoku** [comment]
> > SSR原版本身就不支持ahead，谈何解决？
> 
> 因为SSR已经2年以上不更新了啊。SS也不是一开始就支持的啊

https://github.com/Anankke/SSRR-Windows/issues/3

**Comment by jbxiaoyu** [comment]
> > > SSR原版本身就不支持ahead，谈何解决？
> > 
> > 
> > 因为SSR已经2年以上不更新了啊。SS也不是一开始就支持的啊
> 
> #3

说到底就是SSR太小众了呗，比SS的社群小太多了

**Comment by shikkoku** [comment]
> > > > SSR原版本身就不支持ahead，谈何解决？
> > > 
> > > 
> > > 因为SSR已经2年以上不更新了啊。SS也不是一开始就支持的啊
> > 
> > 
> > #3
> 
> 说到底就是SSR太小众了呗，比SS的社群小太多了

你开什么国际玩笑。

**Comment by 729019004** [comment]
不算小众吧 ss的人必定都先接触ssr
