### ISSUE TITLE
大陆常用域名列表，大陆IP列表还在更新吗？

### ISSUE THREAD

**Issue by reaCodes** [SoDa-GitHub/shadowsocksrr-csharp#2]
PAC的三个规则似乎只有GFWList在维护，大陆常用域名列表，大陆IP列表不维护了吗，有没有其他替代的项目？我用绕过大陆IP多一些。

**Comment by SoDa-GitHub** [comment]
这种issue请发到https://github.com/shadowsocksrr/breakwa11.github.io
