### ISSUE TITLE
5.05版本在任务栏图标右键怎么没有服务器负载均衡？

### ISSUE THREAD

**Issue by ufo1024k** [SoDa-GitHub/shadowsocksrr-csharp#4]
今天更新到5.05后任务栏图标右键怎么没有服务器负载均衡选项？

**Comment by SoDa-GitHub** [comment]
全局设置里依然有。
顺便一提，因为我个人认为这是一个很傻逼的功能，所以默认不再在主菜单中提供。
似乎很多无脑小白酷爱使用这些功能，那还真是“对不住了”。

**Comment by SoDa-GitHub** [comment]
还有，警告一次，发issue归发issue，不要在commit里乱发你的提问，尤其是当你已经提交过issue的情况下。
否则会被block。

**Comment by ufo1024k** [comment]
谢谢，服务器负载均衡选项找到了，用这个功能是因为订阅了地址后，用这个来测试可用地址的延迟。
好的，以后有问题就在这里发了，谢谢提醒

**Comment by Justsoos** [comment]
希望把这个移到右键菜单的第一级菜单（也就是楼主说的那个样子），对于某些小白是傻逼功能。但对于一些高级用户，这是一个非常有价值的 “测速” 辅助功能。
我是这样来用的：

1，设置 “按次序负载均衡”
2，开一个curl www.google.com via SSR 循环 300 times
3，等几分钟，ctrl + 左键打开 “服务器记录”，排序，就能看到所有200多个服务器延迟，通，断，上下传数据，等等详情

如果作者能把上面这个过程加入这个版本，当然更好。这个方法对于大量服务器节点选择，和即便是只有几个服务器，判断那个节点更合适，非常方便有效。
我是听某人说你这个版本SSR作了测速等一些改进，过来试试，不过并没有找到。

**Comment by SoDa-GitHub** [comment]
"不过并没有找到"
good，
那就请你继续用之前的高级版本吧，尊贵的【高级用户】。
我这个版本是不可能把这个移回一级菜单的。

**Comment by Justsoos** [comment]
嗯，我是来试试，正在看你号称要作的SSD新项目。这个用不用没有什么太大关系。
M$ windows 很恶心，但之所以成功，是给用户留了很多条不同的路径达到同一个目标，这也是破墙娃SSR成功至今的要素之一，她（他）很尊重用户需求。其他，不足辩

**Comment by sola97** [comment]
负载均衡我是拿来当代理池用的，写爬虫的时候可以多节点爬，还是挺好用的
