### ISSUE TITLE
About the sequal project "SSD"

### ISSUE THREAD

**Issue by SLAPaper** [SoDa-GitHub/shadowsocksrr-csharp#5]
Noticed the hint about the next "SSD" project in  [Tag 5.0.7](https://github.com/SoDa-GitHub/shadowsocksrr-csharp/releases/tag/5.0.7)

I search through google/bing and SSRR's repos but didn't find related topics, so here open an issue to ask for more infomation:

1. What is the full name of SSD? e.g. ShadowSocksD?
2. Is it still an open-source / freemium / open-access project?
3. If so, what is the repo / homepage address? If not, is there anyway that SSRR users could get hands on it?

Hope for reply!

**Comment by SoDa-GitHub** [comment]
1.ShadowsocksD
2.open-source
3.is still working, windows beta version will release within about 2 weeks (with source code)
