### ISSUE TITLE
Would you like to add switch of ping test?

### ISSUE THREAD

**Issue by faynwol** [SoDa-GitHub/shadowsocksrr-csharp#6]
测延迟功能能否做成选项，可选手动/自动测试？
默认自动测的时候节点前很多都是pending

**Comment by SoDa-GitHub** [comment]
很明显，一个脑回路正常的人应该把导致pending的情况和节点描述一下，而不是优先要求手动测试功能。
难道机智的你觉得手动测试的结果会有什么不一样？

**Comment by faynwol** [comment]
似乎你比较激动，标题would like to do是委婉的说法，并且是问句，没有要求的意思
另外我也解释了为什么会有这种“要求”的原因

最后，我有多个组，每个组都有10个以上节点，第一组1/3pending，第二组全部pending

如果我的描述能够帮助你判断问题，请你保持平稳的情绪回复我，谢谢

**Comment by SoDa-GitHub** [comment]
很明显我说了“优先考虑”，你应当优先考虑的绝不是手动测试，因为就算手动测试也依然屌用没有——自动测试1/3 pending，那么手动测试依然会1/3pending。
脑回路正常的人很容易就知道这一点，而根本不会先想着提出这种“would you like”，另外，我对【语气委婉】没有任何好感。
实际上你似乎连哪些是【有用】信息都搞不清楚，我需要这些信息：
1。当前的模式和代理规则
2。第一组中第一个pending的服务器的地址和端口
3。当前网络状况（是否能翻墙，网速是否顺畅）
